<?php

/**
 * @file
 * Contains islandora_rdm_views_access.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_rdm_views_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_rdm_views_access module.
    case 'help.page.islandora_rdm_views_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Controls access to individual views') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_rdm_views_access_theme() {
  return [
    'islandora_rdm_views_access' => [
      'render element' => 'children',
    ],
  ];
}
